# Part of the famous-games curation tools (G1, docs/FAMOUS_GAMES.md section 4).
# The curated famous games: source spec (lang, title, section, first-moves prefix), factual headers, our words.
# Dates are year-only unless the source states the day.

WCC = "World Chess Championship"


def G(id, era, title, white, black, event, site, date, result, desc, src, round="-", note="-", plies=None):
    return dict(id=id, era=era, title=title, white=white, black=black, event=event, site=site, date=date,
                result=result, desc=desc, src=src, round=round, note=note, plies=plies)


GAMES = [
    # ---------------- Romantic era ----------------
    G("mcdonnell-labourdonnais-1834", "romantic", "McDonnell vs La Bourdonnais, 1834",
      "Alexander McDonnell", "Louis-Charles Mahé de La Bourdonnais", "La Bourdonnais - McDonnell match", "London", "1834.??.??", "0-1",
      "The 16th game of the fourth match between Alexander McDonnell and Louis-Charles Mahé de La Bourdonnais, played in London in 1834.",
      ("en", "McDonnell–La Bourdonnais, match 4, game 16"), round="4.16"),
    G("immortal-game-1851", "romantic", "The Immortal Game",
      "Adolf Anderssen", "Lionel Kieseritzky", "Casual game", "London", "1851.06.21", "1-0",
      "A casual game played in London in 1851, the year of the first international chess tournament; known ever since as the Immortal Game.",
      ("en", "Immortal Game")),
    G("evergreen-game-1852", "romantic", "The Evergreen Game",
      "Adolf Anderssen", "Jean Dufresne", "Casual game", "Berlin", "1852.??.??", "1-0",
      "A casual game played in Berlin in 1852 by Adolf Anderssen and Jean Dufresne; known as the Evergreen Game.",
      ("en", "Evergreen Game")),
    G("paulsen-morphy-1857", "romantic", "Paulsen vs Morphy, New York 1857",
      "Louis Paulsen", "Paul Morphy", "1st American Chess Congress", "New York", "1857.??.??", "0-1",
      "Played at the First American Chess Congress in New York in 1857, which Paul Morphy won.",
      ("en", "Paul Morphy", "Notable games")),
    G("opera-game-1858", "romantic", "The Opera Game",
      "Paul Morphy", "Duke Karl of Brunswick and Count Isouard", "Casual game", "Paris", "1858.??.??", "1-0",
      "Played in 1858 in a box at the Paris opera, against two noblemen consulting together; known as the Opera Game.",
      ("en", "Opera Game")),
    G("morphy-anderssen-1858", "romantic", "Morphy vs Anderssen, Paris 1858",
      "Paul Morphy", "Adolf Anderssen", "Morphy - Anderssen match", "Paris", "1858.??.??", "1-0",
      "The ninth game of the 1858 match in Paris between Paul Morphy and Adolf Anderssen, which Morphy won.",
      ("en", "Paul Morphy", "Morphy vs. Adolf Anderssen, game 9 (1858)"), round="9"),
    G("dubois-steinitz-1862", "romantic", "Dubois vs Steinitz, London 1862",
      "Serafino Dubois", "Wilhelm Steinitz", "London", "London", "1862.??.??", "0-1",
      "Played at the London tournament of 1862, the first international tournament of the future world champion Wilhelm Steinitz.",
      ("de", "Dubois – Steinitz, London 1862")),
    G("immortal-draw-1872", "romantic", "The Immortal Draw",
      "Carl Hamppe", "Philipp Meitner", "Casual game", "Vienna", "1872.??.??", "1/2-1/2",
      "Played in Vienna in 1872 by Carl Hamppe and Philipp Meitner; known as the Immortal Draw.",
      ("en", "Immortal Draw")),

    # ---------------- Classical era ----------------
    G("zukertort-blackburne-1883", "classical", "Zukertort vs Blackburne, London 1883",
      "Johannes Zukertort", "Joseph Henry Blackburne", "London", "London", "1883.??.??", "1-0",
      "Played at the London tournament of 1883, which Johannes Zukertort won ahead of Wilhelm Steinitz.",
      ("de", "Zukertort – Blackburne, London 1883")),
    G("wcc-1886-game-1", "classical", "The first world championship, game 1",
      "Johannes Zukertort", "Wilhelm Steinitz", f"{WCC} 1886", "New York", "1886.01.11", "0-1",
      "The first game of the 1886 match between Wilhelm Steinitz and Johannes Zukertort, the first match for the title of world champion.",
      ("de", "Schachweltmeisterschaft 1886/Partien", "=1. Partie"), round="1"),
    G("wcc-1886-game-20", "classical", "The first world championship, game 20",
      "Wilhelm Steinitz", "Johannes Zukertort", f"{WCC} 1886", "New Orleans", "1886.03.29", "1-0",
      "The 20th and last game of the 1886 match, played in New Orleans; Steinitz won the match and became the first official world champion.",
      ("de", "Schachweltmeisterschaft 1886/Partien", "=20. Partie"), round="20"),
    G("lasker-bauer-1889", "classical", "Lasker vs Bauer, Amsterdam 1889",
      "Emanuel Lasker", "Johann Bauer", "Amsterdam", "Amsterdam", "1889.??.??", "1-0",
      "Played in Amsterdam in 1889 by the 20-year-old Emanuel Lasker, five years before he became world champion.",
      ("en", "Lasker versus Bauer, Amsterdam, 1889"),
      note="de.wikipedia gives moves 6 and 7 in the other order (a transposition to the same position)"),
    G("tarrasch-marco-1892", "classical", "Tarrasch vs Marco, Dresden 1892",
      "Siegbert Tarrasch", "Georg Marco", "Dresden", "Dresden", "1892.??.??", "1-0",
      "Played at the Dresden tournament of 1892, which Siegbert Tarrasch won; the opening trap in it is named after him.",
      ("de", "Tarrasch – Marco, Dresden 1892")),
    G("wcc-1894-game-19", "classical", "Lasker takes the title, 1894",
      "Emanuel Lasker", "Wilhelm Steinitz", f"{WCC} 1894", "Montreal", "1894.??.??", "1-0",
      "Game 19 of the 1894 title match, played in Montreal; with this win Emanuel Lasker took the world championship from Wilhelm Steinitz.",
      ("de", "Schachweltmeisterschaft 1894", "=19. Partie"), round="19"),
    G("steinitz-bardeleben-1895", "classical", "Steinitz vs von Bardeleben, Hastings 1895",
      "Wilhelm Steinitz", "Curt von Bardeleben", "Hastings", "Hastings", "1895.??.??", "1-0",
      "Played at the great Hastings tournament of 1895; Curt von Bardeleben left the hall instead of resigning and lost on time.",
      ("de", "Steinitz – von Bardeleben, Hastings 1895")),
    G("pillsbury-lasker-1896", "classical", "Pillsbury vs Lasker, Saint Petersburg 1896",
      "Harry Nelson Pillsbury", "Emanuel Lasker", "Saint Petersburg 1895-96", "Saint Petersburg", "1896.??.??", "0-1",
      "Played at the four-player tournament in Saint Petersburg in 1895-96, which the world champion Emanuel Lasker won.",
      ("de", "Pillsbury – Lasker, Sankt Petersburg 1896")),
    G("pillsbury-lasker-1904", "classical", "Pillsbury vs Lasker, Cambridge Springs 1904",
      "Harry Nelson Pillsbury", "Emanuel Lasker", "Cambridge Springs", "Cambridge Springs", "1904.??.??", "1-0",
      "Played at Cambridge Springs in 1904, eight years after their game in Saint Petersburg, against the reigning world champion.",
      ("en", "1904 Cambridge Springs International Chess Congress", "Pillsbury's revenge")),
    G("lasker-napier-1904", "classical", "Lasker vs Napier, Cambridge Springs 1904",
      "Emanuel Lasker", "William Ewart Napier", "Cambridge Springs", "Cambridge Springs", "1904.??.??", "1-0",
      "Played at Cambridge Springs in 1904 between the world champion Emanuel Lasker and the young William Napier.",
      ("de", "Lasker – Napier, Cambridge Springs 1904")),
    G("rotlewi-rubinstein-1907", "classical", "Rubinstein's Immortal",
      "Georg Rotlewi", "Akiba Rubinstein", "Lodz", "Lodz", "1907.??.??", "0-1",
      "Played in Lodz in 1907 between Georg Rotlewi and Akiba Rubinstein; known as Rubinstein's Immortal.",
      ("en", "Rotlewi versus Rubinstein")),
    G("wcc-1910-game-10", "classical", "Lasker vs Schlechter, 1910, game 10",
      "Emanuel Lasker", "Carl Schlechter", f"{WCC} 1910", "Berlin", "1910.02.??", "1-0",
      "The tenth and last game of the 1910 title match; Lasker's win levelled the match and he kept the world championship.",
      ("de", "Lasker – Schlechter, Berlin 1910, 10. Wettkampfpartie"), round="10"),
    G("reti-tartakower-1910", "classical", "Réti vs Tartakower, Vienna 1910",
      "Richard Réti", "Savielly Tartakower", "Casual game", "Vienna", "1910.??.??", "1-0",
      "A casual game played in Vienna in 1910 between Richard Réti and Savielly Tartakower; one of the best-known short games.",
      ("de", "Réti – Tartakower, Wien 1910")),
    G("roesch-schlage-1910", "classical", "Roesch vs Schlage, Hamburg 1910",
      "Roesch", "Willi Schlage", "Hamburg", "Hamburg", "1910.??.??", "0-1",
      "Played in Hamburg in 1910; the chess game in the film 2001: A Space Odyssey follows its final moves.",
      ("en", "Poole versus HAL 9000")),
    G("capablanca-bernstein-1911", "classical", "Capablanca vs Bernstein, San Sebastián 1911",
      "José Raúl Capablanca", "Ossip Bernstein", "San Sebastián", "San Sebastián", "1911.??.??", "1-0",
      "Played at San Sebastián in 1911, the tournament José Raúl Capablanca won on his first appearance among Europe's leading masters.",
      ("de", "Capablanca – Bernstein, San Sebastián 1911")),
    G("levitsky-marshall-1912", "classical", "The Gold Coins Game",
      "Stepan Levitsky", "Frank Marshall", "DSB Congress", "Breslau", "1912.07.20", "0-1",
      "Played at Breslau in 1912; known as the Gold Coins Game from the story that spectators showered the board with gold coins.",
      ("en", "Levitsky versus Marshall")),
    G("ed-lasker-thomas-1912", "classical", "Edward Lasker vs Thomas, London 1912",
      "Edward Lasker", "George Alan Thomas", "Casual game", "London", "1912.??.??", "1-0",
      "A casual game played in London in 1912, famous for a king hunt that takes the black king across the whole board.",
      ("en", "Edward Lasker versus Thomas")),
    G("lasker-capablanca-1914", "classical", "Lasker vs Capablanca, Saint Petersburg 1914",
      "Emanuel Lasker", "José Raúl Capablanca", "Saint Petersburg", "Saint Petersburg", "1914.??.??", "1-0",
      "Played in the final stage of the Saint Petersburg tournament of 1914, which Lasker won half a point ahead of Capablanca.",
      ("de", "Lasker – Capablanca, St. Petersburg 1914")),

    # ---------------- Between the wars ----------------
    G("wcc-1921-game-10", "interwar", "Capablanca's title match, game 10",
      "Emanuel Lasker", "José Raúl Capablanca", f"{WCC} 1921", "Havana", "1921.??.??", "0-1",
      "Game 10 of the 1921 title match in Havana, in which José Raúl Capablanca won the world championship from Emanuel Lasker.",
      ("de", "Schachweltmeisterschaft 1921", "=10. Partie"), round="10"),
    G("bogoljubov-alekhine-1922", "interwar", "Bogoljubov vs Alekhine, Hastings 1922",
      "Efim Bogoljubov", "Alexander Alekhine", "Hastings 1922", "Hastings", "1922.??.??", "0-1",
      "Played at Hastings in 1922 between Efim Bogoljubov and Alexander Alekhine, five years before Alekhine became world champion.",
      ("de", "Bogoljubow – Aljechin, Hastings 1922")),
    G("samisch-nimzowitsch-1923", "interwar", "The Immortal Zugzwang Game",
      "Friedrich Sämisch", "Aron Nimzowitsch", "Copenhagen", "Copenhagen", "1923.??.??", "0-1",
      "Played in Copenhagen in 1923 between Friedrich Sämisch and Aron Nimzowitsch; known as the Immortal Zugzwang Game.",
      ("en", "Immortal Zugzwang Game", "", "1. d4 Nf6 2. c4 e6")),
    G("reti-alekhine-1925", "interwar", "Réti vs Alekhine, Baden-Baden 1925",
      "Richard Réti", "Alexander Alekhine", "Baden-Baden", "Baden-Baden", "1925.??.??", "0-1",
      "Played at the Baden-Baden tournament of 1925, which Alexander Alekhine won.",
      ("de", "Réti – Aljechin, Baden-Baden 1925")),
    G("wcc-1927-game-34", "interwar", "Alekhine takes the title, 1927",
      "Alexander Alekhine", "José Raúl Capablanca", f"{WCC} 1927", "Buenos Aires", "1927.??.??", "1-0",
      "Game 34, the last of the 1927 title match in Buenos Aires, with which Alexander Alekhine won the world championship from Capablanca.",
      ("de", "Schachweltmeisterschaft 1927", "=34. Partie"), round="34"),
    G("polish-immortal", "interwar", "The Polish Immortal",
      "Glucksberg", "Miguel Najdorf", "Warsaw", "Warsaw", "1930.??.??", "0-1",
      "Played in Warsaw by the young Miguel Najdorf, on a date that sources give as 1928, 1929 or 1930; known as the Polish Immortal.",
      ("en", "Polish Immortal"),
      note="date disputed (1928-1930); de.wikipedia writes 16...Ngxe5+, the same position as en's 16...Ndxe5+"),
    G("sultan-khan-capablanca-1930", "interwar", "Sultan Khan vs Capablanca, Hastings 1930",
      "Mir Sultan Khan", "José Raúl Capablanca", "Hastings 1930-31", "Hastings", "1930.??.??", "1-0",
      "Played at Hastings in 1930-31; a win by Mir Sultan Khan over the former world champion José Raúl Capablanca.",
      ("en", "Sultan Khan (chess player)", "Notable games", "1. Nf3")),
    G("peruvian-immortal-1934", "interwar", "The Peruvian Immortal",
      "Esteban Canal", "NN", "Simultaneous exhibition", "Budapest", "1934.??.??", "1-0",
      "Played by Esteban Canal of Peru against an amateur in a simultaneous exhibition in Budapest in 1934; known as the Peruvian Immortal.",
      ("en", "Peruvian Immortal")),
    G("wcc-1935-game-26", "interwar", "The Pearl of Zandvoort",
      "Max Euwe", "Alexander Alekhine", f"{WCC} 1935", "Zandvoort", "1935.??.??", "1-0",
      "Game 26 of the 1935 title match, played in Zandvoort; Max Euwe won the match and the world championship. Known as the Pearl of Zandvoort.",
      ("de", "Perle von Zandvoort"), round="26"),
    G("botvinnik-capablanca-1938", "interwar", "Botvinnik vs Capablanca, AVRO 1938",
      "Mikhail Botvinnik", "José Raúl Capablanca", "AVRO", "Rotterdam", "1938.??.??", "1-0",
      "Played in Rotterdam during the AVRO tournament of 1938, between the future champion Mikhail Botvinnik and the former champion Capablanca.",
      ("de", "Botwinnik – Capablanca, Rotterdam 1938")),
    G("uruguayan-immortal-1943", "interwar", "The Uruguayan Immortal",
      "B. Molinari", "Luis Roux Cabral", "Uruguayan Championship", "Uruguay", "1943.??.??", "0-1",
      "Played in the 1943 Uruguayan Championship between B. Molinari and Luis Roux Cabral; known as the Uruguayan Immortal.",
      ("en", "Uruguayan Immortal")),

    # ---------------- Post-war ----------------
    G("wcc-1951-game-23", "postwar", "Botvinnik vs Bronstein, 1951, game 23",
      "Mikhail Botvinnik", "David Bronstein", f"{WCC} 1951", "Moscow", "1951.??.??", "1-0",
      "Game 23 of the 1951 title match in Moscow; Botvinnik's win levelled the match, which ended drawn so that he kept his title.",
      ("de", "Schachweltmeisterschaft 1951", "=23. Partie"), round="23"),
    G("botvinnik-smyslov-1954-game-14", "postwar", "Botvinnik vs Smyslov, 1954, game 14",
      "Mikhail Botvinnik", "Vasily Smyslov", f"{WCC} 1954", "Moscow", "1954.??.??", "1-0",
      "Game 14 of the 1954 title match in Moscow between Mikhail Botvinnik and Vasily Smyslov.",
      ("de", "Botwinnik – Smyslow, Moskau 1954, 14. Wettkampfpartie", "", "1. c4 e5"), round="14"),
    G("game-of-the-century-1956", "postwar", "The Game of the Century",
      "Donald Byrne", "Robert James Fischer", "Rosenwald Memorial", "New York", "1956.10.17", "0-1",
      "Played in New York in 1956 by the 13-year-old Bobby Fischer against Donald Byrne; known as the Game of the Century.",
      ("en", "Game of the Century (chess)")),
    G("wcc-1960-game-1", "postwar", "Tal vs Botvinnik, 1960, game 1",
      "Mikhail Tal", "Mikhail Botvinnik", f"{WCC} 1960", "Moscow", "1960.??.??", "1-0",
      "The first game of the 1960 title match in Moscow, which the 23-year-old Mikhail Tal won to become world champion.",
      ("de", "Schachweltmeisterschaft 1960", "=Partien"), round="1"),
    G("wcc-1960-game-6", "postwar", "Botvinnik vs Tal, 1960, game 6",
      "Mikhail Botvinnik", "Mikhail Tal", f"{WCC} 1960", "Moscow", "1960.??.??", "0-1",
      "Game 6 of the 1960 title match in Moscow, won by the challenger Mikhail Tal with the black pieces.",
      ("de", "Schachweltmeisterschaft 1960", "=6. Partie"), round="6"),
    G("wcc-1961-game-21", "postwar", "Botvinnik vs Tal, 1961, game 21",
      "Mikhail Botvinnik", "Mikhail Tal", f"{WCC} 1961", "Moscow", "1961.??.??", "1-0",
      "Game 21, the last of the 1961 return match in Moscow, in which Mikhail Botvinnik regained the world championship from Mikhail Tal.",
      ("de", "Schachweltmeisterschaft 1961", "=21. Partie"), round="21"),
    G("wcc-1963-game-19", "postwar", "Petrosian vs Botvinnik, 1963, game 19",
      "Tigran Petrosian", "Mikhail Botvinnik", f"{WCC} 1963", "Moscow", "1963.??.??", "1-0",
      "Game 19 of the 1963 title match in Moscow, which Tigran Petrosian won to become world champion.",
      ("de", "Schachweltmeisterschaft 1963", "=19. Partie"), round="19"),
    G("wcc-1966-game-10", "postwar", "Petrosian vs Spassky, 1966, game 10",
      "Tigran Petrosian", "Boris Spassky", f"{WCC} 1966", "Moscow", "1966.??.??", "1-0",
      "Game 10 of the 1966 title match in Moscow, won by the world champion Tigran Petrosian, who kept his title.",
      ("de", "Schachweltmeisterschaft 1966", "=10. Partie"), round="10"),
    G("wcc-1969-game-19", "postwar", "Spassky vs Petrosian, 1969, game 19",
      "Boris Spassky", "Tigran Petrosian", f"{WCC} 1969", "Moscow", "1969.??.??", "1-0",
      "Game 19 of the 1969 title match in Moscow, which Boris Spassky won to become world champion.",
      ("de", "Schachweltmeisterschaft 1969", "=19. Partie"), round="19"),
    G("spassky-bronstein-1960", "postwar", "Spassky vs Bronstein, Leningrad 1960",
      "Boris Spassky", "David Bronstein", "USSR Championship", "Leningrad", "1960.??.??", "1-0",
      "Played in the 1960 Soviet championship in Leningrad; a version of its final position appears in the film From Russia with Love.",
      ("de", "Spasski – Bronstein, UdSSR-Meisterschaft 1960")),
    G("sundin-andersson-1964", "postwar", "Sundin vs Andersson, correspondence 1964",
      "Arvid Sundin", "Erik Andersson", "Correspondence game", "Sweden", "1964.??.??", "1-0",
      "A correspondence game between two Swedish players, 1964-65; its final position was printed on a Swedish postage stamp in 1985.",
      ("de", "Unsterbliche Fernpartie")),
    G("larsen-spassky-1970", "postwar", "Larsen vs Spassky, Belgrade 1970",
      "Bent Larsen", "Boris Spassky", "USSR vs Rest of the World", "Belgrade", "1970.??.??", "0-1",
      "Played at the 1970 match in Belgrade between the Soviet Union and the Rest of the World, on first board.",
      ("de", "Larsen – Spasski, Belgrad 1970")),
    G("wcc-1972-game-6", "postwar", "Fischer vs Spassky, 1972, game 6",
      "Robert James Fischer", "Boris Spassky", f"{WCC} 1972", "Reykjavík", "1972.07.23", "1-0",
      "Game 6 of the 1972 title match in Reykjavík, which Bobby Fischer won to become world champion.",
      ("en", "World Chess Championship 1972", "Game 6"), round="6"),
    G("wcc-1972-game-13", "postwar", "Spassky vs Fischer, 1972, game 13",
      "Boris Spassky", "Robert James Fischer", f"{WCC} 1972", "Reykjavík", "1972.??.??", "0-1",
      "Game 13 of the 1972 title match in Reykjavík, a long game won by Bobby Fischer with the black pieces.",
      ("en", "World Chess Championship 1972", "Game 13"), round="13"),
    G("bagirov-gufeld-1973", "postwar", "Bagirov vs Gufeld, Kirovabad 1973",
      "Vladimir Bagirov", "Eduard Gufeld", "Kirovabad", "Kirovabad", "1973.??.??", "0-1",
      "Played in Kirovabad in 1973; Eduard Gufeld called this win his Mona Lisa.",
      ("de", "Bagirow – Gufeld, Kirowabad 1973")),
    G("wcc-1978-game-32", "postwar", "Karpov vs Korchnoi, 1978, game 32",
      "Anatoly Karpov", "Viktor Korchnoi", f"{WCC} 1978", "Baguio", "1978.??.??", "1-0",
      "Game 32, the last of the 1978 title match in Baguio; Anatoly Karpov's sixth win kept him world champion.",
      ("de", "Schachweltmeisterschaft 1978", "=32. Partie"), round="32"),

    G("wcc-1984-game-32", "postwar", "Kasparov vs Karpov, 1984, game 32",
      "Garry Kasparov", "Anatoly Karpov", f"{WCC} 1984", "Moscow", "1984.??.??", "1-0",
      "Game 32 of the 1984-85 title match in Moscow, Garry Kasparov's first win of a match that was later stopped without a result.",
      ("de", "Schachweltmeisterschaft 1984", "=32. Partie"), round="32"),

    # ---------------- Karpov and Kasparov ----------------
    G("wcc-1985-game-16", "kasparov", "Karpov vs Kasparov, 1985, game 16",
      "Anatoly Karpov", "Garry Kasparov", f"{WCC} 1985", "Moscow", "1985.??.??", "0-1",
      "Game 16 of the 1985 title match in Moscow, won by the challenger Garry Kasparov with the black pieces.",
      ("en", "Karpov–Kasparov rivalry", "Game 16"), round="16"),
    G("wcc-1985-game-24", "kasparov", "Kasparov takes the title, 1985",
      "Anatoly Karpov", "Garry Kasparov", f"{WCC} 1985", "Moscow", "1985.11.09", "0-1",
      "Game 24, the last of the 1985 title match in Moscow; Kasparov's win made him, at 22, the youngest world champion up to then.",
      ("de", "Schachweltmeisterschaft 1985", "=24. Partie"), round="24"),
    G("wcc-1986-game-16", "kasparov", "Kasparov vs Karpov, 1986, game 16",
      "Garry Kasparov", "Anatoly Karpov", f"{WCC} 1986", "Leningrad", "1986.??.??", "1-0",
      "Game 16 of the 1986 title match, played in Leningrad, between Garry Kasparov and Anatoly Karpov.",
      ("de", "Schachweltmeisterschaft 1986/Partien", "=16. Partie"), round="16"),
    G("wcc-1986-game-22", "kasparov", "Kasparov vs Karpov, 1986, game 22",
      "Garry Kasparov", "Anatoly Karpov", f"{WCC} 1986", "Leningrad", "1986.??.??", "1-0",
      "Game 22 of the 1986 title match in Leningrad; with this win Garry Kasparov reached the 12 points he needed to keep his title.",
      ("en", "World Chess Championship 1986", "Game 22"), round="22"),
    G("wcc-1990-game-20", "kasparov", "Kasparov vs Karpov, 1990, game 20",
      "Garry Kasparov", "Anatoly Karpov", f"{WCC} 1990", "Lyon", "1990.??.??", "1-0",
      "Game 20 of the 1990 title match, the fifth match between Garry Kasparov and Anatoly Karpov, played in Lyon.",
      ("de", "Schachweltmeisterschaft 1990", "=20. Partie"), round="20"),
    G("wcc-1987-game-24", "kasparov", "Kasparov vs Karpov, 1987, game 24",
      "Garry Kasparov", "Anatoly Karpov", f"{WCC} 1987", "Seville", "1987.12.??", "1-0",
      "Game 24, the last of the 1987 title match in Seville; Garry Kasparov needed a win to keep his title, and won.",
      ("de", "Schachweltmeisterschaft 1987", "=24. Partie"), round="24"),
    G("ivanchuk-yusupov-1991", "kasparov", "Ivanchuk vs Yusupov, Brussels 1991",
      "Vassily Ivanchuk", "Artur Yusupov", "Candidates quarter-final", "Brussels", "1991.??.??", "0-1",
      "Played in Brussels in 1991 in the Candidates quarter-final match between Vassily Ivanchuk and Artur Yusupov.",
      ("de", "Iwantschuk – Jussupow, Brüssel 1991")),
    G("kasparovs-immortal-1999", "kasparov", "Kasparov's Immortal",
      "Garry Kasparov", "Veselin Topalov", "Hoogovens", "Wijk aan Zee", "1999.01.20", "1-0",
      "Played at the Hoogovens tournament in Wijk aan Zee in 1999 between Garry Kasparov and Veselin Topalov; known as Kasparov's Immortal.",
      ("en", "Kasparov's Immortal")),
    G("kasparov-vs-the-world-1999", "kasparov", "Kasparov versus the World",
      "Garry Kasparov", "The World", "Kasparov versus the World", "Internet", "1999.??.??", "1-0",
      "Played over the internet in 1999: Garry Kasparov against moves chosen by a vote of thousands of players from many countries.",
      ("en", "Kasparov versus the World")),
    G("anand-radjabov-2003", "kasparov", "Anand vs Radjabov, Dortmund 2003",
      "Viswanathan Anand", "Teimour Radjabov", "Dortmund", "Dortmund", "2003.??.??", "0-1",
      "Played at Dortmund in 2003, when Teimour Radjabov was 16, against Viswanathan Anand.",
      ("de", "Anand – Rəcəbov, Dortmund 2003")),

    # ---------------- Modern era ----------------
    G("wcc-2006-game-2", "modern", "Topalov vs Kramnik, 2006, game 2",
      "Veselin Topalov", "Vladimir Kramnik", f"{WCC} 2006", "Elista", "2006.??.??", "0-1",
      "Game 2 of the 2006 reunification match in Elista between Veselin Topalov and Vladimir Kramnik.",
      ("de", "Schachweltmeisterschaft 2006/Partien", "=2. Partie"), round="2"),
    G("wcc-2006-tiebreak-4", "modern", "Kramnik vs Topalov, 2006, rapid tiebreak",
      "Vladimir Kramnik", "Veselin Topalov", f"{WCC} 2006 (rapid tiebreak)", "Elista", "2006.10.13", "1-0",
      "The fourth rapid game of the 2006 tiebreak in Elista; Vladimir Kramnik's win reunified the world championship title.",
      ("de", "Schachweltmeisterschaft 2006/Partien", "=4. Schnellschachpartie"), round="4",
      note="en.wikipedia's Game 16 writes one move differently and reaches the same final position"),
    G("wcc-2008-game-6", "modern", "Anand vs Kramnik, 2008, game 6",
      "Viswanathan Anand", "Vladimir Kramnik", f"{WCC} 2008", "Bonn", "2008.??.??", "1-0",
      "Game 6 of the 2008 title match in Bonn, which Viswanathan Anand won.",
      ("en", "World Chess Championship 2008", "Game 6"), round="6"),
    G("wcc-2010-game-12", "modern", "Topalov vs Anand, 2010, game 12",
      "Veselin Topalov", "Viswanathan Anand", f"{WCC} 2010", "Sofia", "2010.05.11", "0-1",
      "Game 12, the last of the 2010 title match in Sofia; Viswanathan Anand's win decided the match.",
      ("de", "Schachweltmeisterschaft 2010", "=12. Partie"), round="12"),
    G("wcc-2012-game-8", "modern", "Anand vs Gelfand, 2012, game 8",
      "Viswanathan Anand", "Boris Gelfand", f"{WCC} 2012", "Moscow", "2012.05.21", "1-0",
      "Game 8 of the 2012 title match in Moscow; at 17 moves, one of the shortest decisive games in world championship history.",
      ("en", "World Chess Championship 2012", "Game 8"), round="8"),
    G("anands-immortal-2013", "modern", "Anand's Immortal",
      "Levon Aronian", "Viswanathan Anand", "Tata Steel", "Wijk aan Zee", "2013.01.15", "0-1",
      "Played in round 4 of the Tata Steel tournament in Wijk aan Zee in 2013; known as Anand's Immortal.",
      ("en", "Anand's Immortal"), round="4"),
    G("wcc-2013-game-5", "modern", "Carlsen vs Anand, 2013, game 5",
      "Magnus Carlsen", "Viswanathan Anand", f"{WCC} 2013", "Chennai", "2013.??.??", "1-0",
      "Game 5 of the 2013 title match in Chennai, Magnus Carlsen's first win on the way to the world championship.",
      ("en", "World Chess Championship 2013", "Game 5"), round="5"),
    G("wcc-2013-game-6", "modern", "Anand vs Carlsen, 2013, game 6",
      "Viswanathan Anand", "Magnus Carlsen", f"{WCC} 2013", "Chennai", "2013.??.??", "0-1",
      "Game 6 of the 2013 title match in Chennai, Magnus Carlsen's second win of the match.",
      ("en", "World Chess Championship 2013", "Game 6"), round="6"),
    G("wcc-2013-game-9", "modern", "Anand vs Carlsen, 2013, game 9",
      "Viswanathan Anand", "Magnus Carlsen", f"{WCC} 2013", "Chennai", "2013.??.??", "0-1",
      "Game 9 of the 2013 title match in Chennai, Magnus Carlsen's third win of the match.",
      ("en", "World Chess Championship 2013", "Game 9"), round="9"),
    G("wcc-2014-game-11", "modern", "Carlsen vs Anand, 2014, game 11",
      "Magnus Carlsen", "Viswanathan Anand", f"{WCC} 2014", "Sochi", "2014.11.23", "1-0",
      "Game 11 of the 2014 title match in Sochi; Magnus Carlsen's win kept his world championship.",
      ("en", "World Chess Championship 2014", "Game 11"), round="11"),
    G("wcc-2016-game-10", "modern", "Carlsen vs Karjakin, 2016, game 10",
      "Magnus Carlsen", "Sergey Karjakin", f"{WCC} 2016", "New York", "2016.??.??", "1-0",
      "Game 10 of the 2016 title match in New York, Magnus Carlsen's first win of the match, which levelled the score.",
      ("en", "World Chess Championship 2016", "Game 10"), round="10"),
    G("wcc-2016-tiebreak-4", "modern", "Carlsen vs Karjakin, 2016, rapid tiebreak",
      "Magnus Carlsen", "Sergey Karjakin", f"{WCC} 2016 (rapid tiebreak)", "New York", "2016.11.30", "1-0",
      "The fourth rapid game of the 2016 tiebreak in New York, played on Magnus Carlsen's birthday; his win kept the title.",
      ("de", "Schachweltmeisterschaft 2016", "=Schnellschach-Partie 4"), round="4"),
    G("wcc-2018-tiebreak-3", "modern", "Carlsen vs Caruana, 2018, rapid tiebreak",
      "Magnus Carlsen", "Fabiano Caruana", f"{WCC} 2018 (rapid tiebreak)", "London", "2018.11.28", "1-0",
      "The third rapid game of the 2018 tiebreak in London, after twelve drawn games; Magnus Carlsen won all three rapid games and kept his title.",
      ("de", "Schachweltmeisterschaft 2018", "=Schnellschach-Partie 3"), round="3"),
    G("wcc-2021-game-6", "modern", "Carlsen vs Nepomniachtchi, 2021, game 6",
      "Magnus Carlsen", "Ian Nepomniachtchi", f"{WCC} 2021", "Dubai", "2021.12.03", "1-0",
      "Game 6 of the 2021 title match in Dubai; at 136 moves, the longest game ever played in a world championship match.",
      ("en", "Carlsen versus Nepomniachtchi, World Chess Championship 2021, Game 6"), round="6"),
    G("wcc-2021-game-8", "modern", "Carlsen vs Nepomniachtchi, 2021, game 8",
      "Magnus Carlsen", "Ian Nepomniachtchi", f"{WCC} 2021", "Dubai", "2021.??.??", "1-0",
      "Game 8 of the 2021 title match in Dubai, Magnus Carlsen's second win of the match.",
      ("de", "Schachweltmeisterschaft 2021/Partien", "=8. Partie"), round="8"),
    G("wcc-2023-game-4", "modern", "Ding vs Nepomniachtchi, 2023, game 4",
      "Ding Liren", "Ian Nepomniachtchi", f"{WCC} 2023", "Astana", "2023.??.??", "1-0",
      "Game 4 of the 2023 title match in Astana, Ding Liren's first win of the match.",
      ("de", "Schachweltmeisterschaft 2023/Partien", "=4. Partie", "1. c4"), round="4"),
    G("wcc-2023-game-12", "modern", "Ding vs Nepomniachtchi, 2023, game 12",
      "Ding Liren", "Ian Nepomniachtchi", f"{WCC} 2023", "Astana", "2023.??.??", "1-0",
      "Game 12 of the 2023 title match in Astana, a win by Ding Liren that levelled the match.",
      ("de", "Schachweltmeisterschaft 2023/Partien", "=12. Partie"), round="12"),
    G("wcc-2023-tiebreak-4", "modern", "Nepomniachtchi vs Ding, 2023, rapid tiebreak",
      "Ian Nepomniachtchi", "Ding Liren", f"{WCC} 2023 (rapid tiebreak)", "Astana", "2023.04.30", "0-1",
      "The fourth rapid game of the 2023 tiebreak in Astana; Ding Liren's win made him the first world champion from China.",
      ("de", "Schachweltmeisterschaft 2023/Partien", "=4. Partie", "1. e4"), round="4"),
    G("wcc-2024-game-1", "modern", "Gukesh vs Ding, 2024, game 1",
      "Gukesh Dommaraju", "Ding Liren", f"{WCC} 2024", "Singapore", "2024.11.25", "0-1",
      "The first game of the 2024 title match in Singapore, won by the defending champion Ding Liren with the black pieces.",
      ("de", "Schachweltmeisterschaft 2024/Partien", "=1. Partie"), round="1"),
    G("wcc-2024-game-3", "modern", "Gukesh vs Ding, 2024, game 3",
      "Gukesh Dommaraju", "Ding Liren", f"{WCC} 2024", "Singapore", "2024.11.27", "1-0",
      "Game 3 of the 2024 title match in Singapore, Gukesh Dommaraju's first win of the match.",
      ("de", "Schachweltmeisterschaft 2024/Partien", "=3. Partie"), round="3"),
    G("wcc-2024-game-11", "modern", "Gukesh vs Ding, 2024, game 11",
      "Gukesh Dommaraju", "Ding Liren", f"{WCC} 2024", "Singapore", "2024.??.??", "1-0",
      "Game 11 of the 2024 title match in Singapore, which put Gukesh Dommaraju ahead in the match for the first time.",
      ("de", "Schachweltmeisterschaft 2024/Partien", "=11. Partie"), round="11"),
    G("wcc-2024-game-14", "modern", "Ding vs Gukesh, 2024, game 14",
      "Ding Liren", "Gukesh Dommaraju", f"{WCC} 2024", "Singapore", "2024.12.12", "0-1",
      "Game 14, the last of the 2024 title match in Singapore; the win made the 18-year-old Gukesh Dommaraju the youngest undisputed world champion.",
      ("de", "Schachweltmeisterschaft 2024/Partien", "=14. Partie"), round="14"),

    # ---------------- Humans against computers ----------------
    G("deep-blue-kasparov-1996-game-1", "computers", "Deep Blue vs Kasparov, 1996, game 1",
      "Deep Blue", "Garry Kasparov", "Deep Blue - Kasparov match", "Philadelphia", "1996.02.10", "1-0",
      "The first game of the 1996 match in Philadelphia, the first game a computer won against a reigning world champion under tournament conditions.",
      ("en", "Deep Blue versus Kasparov, 1996, Game 1"), round="1"),
    G("kasparov-deep-blue-1996-game-2", "computers", "Kasparov vs Deep Blue, 1996, game 2",
      "Garry Kasparov", "Deep Blue", "Deep Blue - Kasparov match", "Philadelphia", "1996.02.11", "1-0",
      "The second game of the 1996 match in Philadelphia, which Garry Kasparov won to level the score; he went on to win the match.",
      ("es", "Deep Blue versus Garri Kasparov", "", "1. Nf3 d5 2. d4 e6"), round="2"),
    G("kasparov-deep-blue-1996-game-6", "computers", "Kasparov vs Deep Blue, 1996, game 6",
      "Garry Kasparov", "Deep Blue", "Deep Blue - Kasparov match", "Philadelphia", "1996.02.17", "1-0",
      "The sixth and last game of the 1996 match in Philadelphia; Garry Kasparov's win gave him the match by 4 points to 2.",
      ("es", "Deep Blue versus Garri Kasparov", "1996 6ª partida Kasparov contra Deep Blue"), round="6"),
    G("kasparov-deep-blue-1997-game-1", "computers", "Kasparov vs Deep Blue, 1997, game 1",
      "Garry Kasparov", "Deep Blue", "Deep Blue - Kasparov rematch", "New York", "1997.05.03", "1-0",
      "The first game of the 1997 rematch in New York, won by Garry Kasparov.",
      ("es", "Deep Blue versus Garri Kasparov", "", "1. Nf3 d5 2. g3 Bg4 3. b3"), round="1"),
    G("deep-blue-kasparov-1997-game-6", "computers", "Deep Blue vs Kasparov, 1997, game 6",
      "Deep Blue", "Garry Kasparov", "Deep Blue - Kasparov rematch", "New York", "1997.05.11", "1-0",
      "The sixth and last game of the 1997 rematch in New York; Deep Blue's win made it the first computer to beat a world champion in a match.",
      ("en", "Deep Blue versus Kasparov, 1997, Game 6"), round="6"),
]
