package net.palaya.chessanalyzer.core.analysis

/**
 * GENERATED by `scripts/verify_tactic_references.py` from `fixtures/tactic_references.json`.
 * Do not edit by hand: every entry here passed python-chess legality, the pattern's own structural
 * check and (where the claim is material or mate) a small exhaustive solver. Edit the script's
 * REFS table, re-run it, and let it regenerate this file. `TacticReferenceCorpusTest` asserts this
 * table and the JSON are identical and replays every line through `:core`'s own move generator.
 */
internal object TacticReferenceCorpus {
    val entries: List<TacticReference> = listOf(
        TacticReference(
            type = TacticType.FORK,
            fen = "2r3k1/5ppp/8/3N4/8/8/5PPP/6K1 w - - 0 1",
            solutionSan = listOf("Ne7+"),
            teachingPoint = "The knight checks the king and hits the rook at the same time; the king must move and the rook drops."
        ),
        TacticReference(
            type = TacticType.PAWN_FORK,
            fen = "4k3/8/8/3n1n2/8/4P3/8/4K3 w - - 0 1",
            solutionSan = listOf("e4"),
            teachingPoint = "One pawn push attacks two pieces at once, and neither can take it - the cheapest attacker always wins the exchange."
        ),
        TacticReference(
            type = TacticType.PIN_ABSOLUTE,
            fen = "4k3/3n4/8/8/8/8/8/4KB2 w - - 0 1",
            solutionSan = listOf("Bb5"),
            teachingPoint = "A piece pinned against its own king is frozen - it cannot legally move, so it defends nothing."
        ),
        TacticReference(
            type = TacticType.PIN_RELATIVE,
            fen = "3qk3/8/5n2/8/8/8/8/2B1K3 w - - 0 1",
            solutionSan = listOf("Bg5"),
            teachingPoint = "The knight may legally move, but doing so loses the queen behind it - a relative pin."
        ),
        TacticReference(
            type = TacticType.SKEWER,
            fen = "rk6/8/8/8/8/8/8/6KR w - - 0 1",
            solutionSan = listOf("Rh8+"),
            teachingPoint = "Check the king along a line with a piece behind it; when the king steps aside, that piece falls."
        ),
        TacticReference(
            type = TacticType.BACK_RANK_MATE,
            fen = "6k1/5ppp/8/8/8/8/8/R5K1 w - - 0 1",
            solutionSan = listOf("Ra8#"),
            teachingPoint = "A king walled in by its own pawns has no escape; a rook arriving on the back rank is mate."
        ),
        TacticReference(
            type = TacticType.SMOTHERED_MATE,
            fen = "6rk/6pp/8/6N1/8/8/8/6K1 w - - 0 1",
            solutionSan = listOf("Nf7#"),
            teachingPoint = "The king's own pieces steal every flight square, so a lone knight delivers mate."
        ),
        TacticReference(
            type = TacticType.DOUBLE_CHECK,
            fen = "4k3/8/8/8/4B3/8/8/4R1K1 w - - 0 1",
            solutionSan = listOf("Bc6+"),
            teachingPoint = "The bishop checks and uncovers the rook behind it. Two checks at once cannot be blocked or captured - the king MUST move."
        ),
        TacticReference(
            type = TacticType.DISCOVERED_CHECK,
            fen = "4k3/8/8/8/4N3/8/8/4R1K1 w - - 0 1",
            solutionSan = listOf("Ng5+"),
            teachingPoint = "Moving one piece out of the way lets the piece behind it give check - the mover is free to go anywhere."
        ),
        TacticReference(
            type = TacticType.DISCOVERED_ATTACK,
            fen = "k3q3/8/8/8/4N3/8/8/4R1K1 w - - 0 1",
            solutionSan = listOf("Ng5"),
            teachingPoint = "Stepping aside unmasks an attack from the piece behind - here the rook suddenly hits the queen."
        ),
        TacticReference(
            type = TacticType.HANGING_PIECE,
            fen = "rnbqkb1r/pppp1ppp/8/4n3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 1",
            solutionSan = listOf("Nxe5"),
            teachingPoint = "An undefended piece can simply be taken for free - check what is hanging before every move."
        ),
        TacticReference(
            type = TacticType.REMOVING_THE_DEFENDER,
            fen = "7k/8/3p4/4p3/1B6/5N2/8/4K3 w - - 0 1",
            solutionSan = listOf("Bxd6", "Kg8", "Nxe5"),
            teachingPoint = "The e5 pawn was only held by its neighbour. Take the defender first, and the defended piece falls next."
        ),
        TacticReference(
            type = TacticType.TRAPPED_PIECE,
            fen = "4k3/8/8/8/8/8/5KPb/8 w - - 0 1",
            solutionSan = listOf("g3"),
            teachingPoint = "A piece deep in enemy territory can run out of squares - every retreat here simply loses the bishop."
        ),
        TacticReference(
            type = TacticType.PROMOTION_TACTIC,
            fen = "8/P7/8/8/8/8/8/K6k w - - 0 1",
            solutionSan = listOf("a8=Q+"),
            teachingPoint = "A pawn reaching the last rank becomes a queen - a passed pawn is a queen waiting to happen."
        ),
        TacticReference(
            type = TacticType.UNDERPROMOTION,
            fen = "8/4k1P1/8/8/8/8/8/K7 w - - 0 1",
            solutionSan = listOf("g8=N+"),
            teachingPoint = "Sometimes a knight beats a queen: only the knight gives check here."
        ),
        TacticReference(
            type = TacticType.DEFLECTION,
            fen = "3q2k1/2p2ppp/8/8/8/2Q5/5PPP/4R1K1 w - - 0 1",
            solutionSan = listOf("Qxc7", "Qxc7", "Re8#"),
            teachingPoint = "The queen is the only guard of the back rank. Attack it with something it must take, and the guard is gone."
        ),
        TacticReference(
            type = TacticType.DECOY,
            fen = "7k/2q3pp/8/6N1/8/8/5PPP/3R2K1 w - - 0 1",
            solutionSan = listOf("Rd8+", "Qxd8", "Nf7+", "Kg8", "Nxd8"),
            teachingPoint = "Give up the rook to drag the queen onto d8 - the one square where the knight forks king and queen."
        ),
        TacticReference(
            type = TacticType.OVERLOADED_PIECE,
            fen = "4r1k1/1n1q1ppp/8/8/8/5B2/5PPP/R3R1K1 w - - 0 1",
            solutionSan = listOf("Rxe8+", "Qxe8", "Bxb7"),
            teachingPoint = "One queen was guarding two things. Take the first, it must recapture, and the second is left hanging."
        ),
        TacticReference(
            type = TacticType.CLEARANCE,
            fen = "5rk1/5pp1/8/7R/8/3B4/6P1/3Q2K1 w - - 0 1",
            solutionSan = listOf("Rh8+", "Kxh8", "Qh5+", "Kg8", "Qh7#"),
            teachingPoint = "The rook is sitting on the square the queen needs, so it leaves with check - and the queen lands on h5 next move."
        ),
        TacticReference(
            type = TacticType.ZWISCHENZUG,
            fen = "3qk3/ppp2ppp/8/4p3/2B1P3/5b2/PPP2PPP/3QK3 w - - 0 1",
            solutionSan = listOf("Bxf7+", "Kxf7", "Qxd8"),
            teachingPoint = "Do not recapture on autopilot. First a check that drags the king off the queen's defence, then take the queen."
        ),
        TacticReference(
            type = TacticType.DOUBLE_ATTACK,
            fen = "4k3/5ppp/q7/8/4N3/8/5PPP/4R1K1 w - - 0 1",
            solutionSan = listOf("Nc5+", "Kd8", "Nxa6"),
            teachingPoint = "One move, two threats from two different pieces: the rook behind gives check, the knight itself hits the queen. Only one can be answered."
        ),
        TacticReference(
            type = TacticType.MATE_NET,
            fen = "7k/4Nppp/8/8/4Q3/R7/8/6K1 w - - 0 1",
            solutionSan = listOf("Qxh7+", "Kxh7", "Rh3#"),
            teachingPoint = "A queen sacrifice pulls the king into a net where every square is already covered - then the rook lifts and it is over."
        ),
        TacticReference(
            type = TacticType.WINDMILL,
            fen = "3q1n1k/pppbnpRp/5B2/8/8/8/5PPP/6K1 w - - 0 1",
            solutionSan = listOf("Rxf7+", "Kg8", "Rg7+", "Kh8", "Rxe7+", "Kg8", "Rg7+", "Kh8", "Rxd7+"),
            teachingPoint = "Discovered check, direct check, discovered check: the king is shuttled back and forth while the rook eats the whole rank."
        ),
        TacticReference(
            type = TacticType.GREEK_GIFT,
            fen = "r1bq1rk1/ppp1bppp/2n1p3/3pP3/3P4/3B1N2/PPP2PPP/R2Q1RK1 w - - 0 1",
            solutionSan = listOf("Bxh7+", "Kxh7", "Ng5+", "Kg8", "Qh5"),
            teachingPoint = "The classic bishop sacrifice on h7: the king is pulled out, the knight checks, and the queen arrives with a mate threat."
        ),
        TacticReference(
            type = TacticType.PASSED_PAWN_BREAKTHROUGH,
            fen = "7k/ppp5/8/PPP5/8/8/8/7K w - - 0 1",
            solutionSan = listOf("b6", "cxb6", "a6", "bxa6", "c6"),
            teachingPoint = "Three pawns against three: give up two of them and the third becomes a passed pawn nobody can catch."
        ),
        TacticReference(
            type = TacticType.DESPERADO,
            fen = "3rk3/8/8/4p3/3Q4/8/PPP2PPP/3K4 w - - 0 1",
            solutionSan = listOf("Qxd8+", "Kxd8"),
            teachingPoint = "The queen is lost whatever it does - the rook pins it and the pawn attacks it - so it sells itself for a rook rather than for nothing."
        ),
        TacticReference(
            type = TacticType.PERPETUAL_CHECK,
            fen = "6k1/6p1/8/3p4/8/8/qr2Q3/6K1 w - - 0 1",
            solutionSan = listOf("Qe8+", "Kh7", "Qh5+", "Kg8", "Qe8+", "Kh7", "Qh5+", "Kg8"),
            teachingPoint = "Down a queen and a rook, White cannot win - but the king cannot escape the checks either, and repetition is a draw."
        ),
        TacticReference(
            type = TacticType.STALEMATE_TRICK,
            fen = "r6k/8/1q6/3Q4/8/7p/7P/7K w - - 0 1",
            solutionSan = listOf("Qg8+", "Kxg8"),
            teachingPoint = "Hopelessly lost, White has one move left: a queen check that MUST be captured - and then White has no legal move at all."
        )
    )
}
