package net.palaya.chessanalyzer.core.text

/**
 * The rephrase prompt, versioned (docs/LLM_REPHRASE_DESIGN.md §4). [VERSION] is part of every cache key
 * and must equal `rephrase.prompt.version` in `vendor/models/MODELS.lock` (`RephrasePromptTest`).
 *
 * The prompt is one fixed prefix (system rules + few-shot pairs, identical for every request, so a backend
 * keeps it in its KV cache) and a short per-request suffix (the fact list and the text). The fact list is
 * generated by [ClaimChecker.facts], the extractor the output is then held to, so the model sees exactly
 * what it will be checked against. The few-shot outputs pass the checker by construction (a host test
 * asserts it).
 */
object RephrasePrompt {

    const val VERSION = 1

    enum class Family {
        /** Qwen2.5 Instruct: ChatML. */
        QWEN2,

        /** Qwen3: ChatML, with an empty think block in the answer to switch thinking off. */
        QWEN3,
    }

    val SYSTEM: String = """
        You polish chess commentary for a game-review app. Rewrite the text under ## Text so it reads like a calm, professional commentator: natural, clear, varied sentences. Rules, in order of importance:
        1. Keep every fact. Every move, square, piece, side, number, name and chess term listed under ## Facts must appear with the same meaning. Add nothing: no new tactic, threat, plan, praise, blame, opinion or evaluation.
        2. Never say a move wins, loses, forces, threatens, attacks or traps anything unless the text already says so. Keep every "not" and "no".
        3. If the text ends with "Better was <move>", keep that sentence last and unchanged.
        4. Keep "you", "your opponent", "White" and "Black" exactly as used; never change who does what.
        5. Write moves and squares exactly as the text does. In narration they are spoken words: keep "h five", never write "h5".
        6. About the same length. Plain prose: no lists, quotes, headings, notes or preamble.
        Output only the rewritten text. If you cannot keep every fact, output the text unchanged.
    """.trimIndent()

    data class Example(val surface: RephraseSurface, val text: String, val output: String)

    /** Four fixed pairs: a praised move, an error card, a narration beat, and a text best left as it is. */
    val EXAMPLES: List<Example> = listOf(
        Example(
            RephraseSurface.CARD,
            "Qf3 is the engine's first choice. It traps the queen on g5: every square it can reach loses material.",
            "The engine's first choice is Qf3. It traps the queen on g5, since every square it can reach loses material."
        ),
        Example(
            RephraseSurface.CARD,
            "Now White can play Nxg7+, which sets a forced mate in 5 in motion. That takes Black from clearly worse to decisively lost. Better was Ba6.",
            "White can now answer with Nxg7+, setting a forced mate in 5 in motion, and Black goes from clearly worse to decisively lost. Better was Ba6."
        ),
        Example(
            RephraseSurface.NARRATION,
            "Black takes the rook on g one with the bishop. And the chance is gone. It does not come back. That's about level turning into clearly worse in a single move.",
            "Black's bishop takes the rook on g one, and the chance is gone; it does not come back. In a single move, about level turns into clearly worse."
        ),
        Example(
            RephraseSurface.CARD,
            "Nxb5 sacrifices the knight on b5.",
            "Nxb5 sacrifices the knight on b5."
        ),
    )

    private val SPOKEN = arrayOf("one", "two", "three", "four", "five", "six", "seven", "eight")

    private fun spoken(square: String): String =
        if (square.length >= 2 && square[1] in '1'..'8') "${square[0]} ${SPOKEN[square[1] - '1']}${square.substring(2)}" else square

    private fun list(items: Collection<String>): String = if (items.isEmpty()) "none" else items.joinToString(", ")

    /** The two lines of facts the model is shown, from the checker's own extraction. */
    fun factLines(text: String, surface: RephraseSurface): String {
        val f = ClaimChecker.facts(text, surface)
        val squares = if (surface == RephraseSurface.NARRATION) f.squares.map(::spoken) else f.squares
        val pieces = f.pieceSquares.sorted().map {
            val (p, s) = it.split('@')
            "$p on " + if (surface == RephraseSurface.NARRATION) spoken(s) else s
        } + f.pieces.distinct().filter { p -> f.pieceSquares.none { it.startsWith("$p@") } }
        val players = f.players.distinct().map {
            when (it) {
                "WHITE" -> "White"
                "BLACK" -> "Black"
                "YOU" -> "you"
                else -> "your opponent"
            }
        }
        val bands = if (f.bands.isEmpty()) "none" else f.bands.joinToString(" -> ")
        val line1 = "moves: ${list(f.moves)} | squares: ${list(squares.distinct())} | pieces: ${list(pieces)} | " +
            "players: ${list(players)} | numbers: ${list(f.numbers.distinct())}"
        val line2 = "terms: ${list(f.terms.keys)} | bands: $bands | names: ${list(f.names.sorted())} | " +
            "surface: ${surface.name.lowercase()}"
        return "$line1\n$line2"
    }

    fun userTurn(text: String, surface: RephraseSurface): String =
        "## Facts\n${factLines(text, surface)}\n## Text\n${ClaimChecker.normalize(text)}"

    private const val START = "<|im_start|>"
    private const val END = "<|im_end|>"
    private const val NO_THINK = "<think>\n\n</think>\n\n"

    /**
     * The fixed part of every prompt: system, the few-shot turns, and the opening of the final user turn.
     * Byte-identical across requests, so the backend reuses its KV cache for it.
     */
    fun prefix(family: Family = Family.QWEN2): String = buildString {
        append(START).append("system\n").append(SYSTEM).append(END).append('\n')
        for (e in EXAMPLES) {
            append(START).append("user\n").append(userTurn(e.text, e.surface)).append(END).append('\n')
            append(START).append("assistant\n").append(e.output).append(END).append('\n')
        }
        append(START).append("user\n")
    }

    /** The per-request tail that follows [prefix]: the facts, the text, and the open assistant turn. */
    fun suffix(text: String, surface: RephraseSurface, family: Family = Family.QWEN2): String = buildString {
        append(userTurn(text, surface)).append(END).append('\n')
        append(START).append("assistant\n")
        if (family == Family.QWEN3) append(NO_THINK)
    }

    fun full(text: String, surface: RephraseSurface, family: Family = Family.QWEN2): String =
        prefix(family) + suffix(text, surface, family)

    /** The generation cap: twice the original's tokens plus 16 (design §2.2). */
    fun maxTokens(originalTokens: Int): Int = 2 * originalTokens + 16

    private val THINK = Regex("<think>.*?</think>", RegexOption.DOT_MATCHES_ALL)

    /**
     * The model's raw text made comparable: stop markers and an (empty) think block removed, the first
     * paragraph only, one pair of wrapping quotes stripped. Anything else (a list, a preamble, a second
     * line) is left for [ClaimChecker] to reject.
     */
    fun cleanOutput(raw: String, surface: RephraseSurface = RephraseSurface.CARD): String {
        val t = cleanRaw(raw)
        // Narration is heard: a bare square the model wrote as notation ("h5") goes back to the spoken form
        // ("h five"), the same fact in the voice's words. SAN moves are left for the checker to refuse.
        return if (surface == RephraseSurface.NARRATION) BARE_SQUARE.replace(t) { spoken(it.value) } else t
    }

    private val BARE_SQUARE = Regex("(?<![A-Za-z0-9])[a-h][1-8](?![A-Za-z0-9+#=])")

    private fun cleanRaw(raw: String): String {
        var t = raw
        for (stop in listOf(END, "<|endoftext|>", START)) t = t.substringBefore(stop)
        t = THINK.replace(t, "").trim()
        t = t.substringBefore("\n\n").trim()
        val pairs = listOf('"' to '"', '“' to '”')
        for ((a, b) in pairs) {
            val once = if (a == b) t.count { it == a } == 2 else t.count { it == a } == 1 && t.count { it == b } == 1
            if (t.length > 2 && t.first() == a && t.last() == b && once) {
                t = t.substring(1, t.length - 1).trim()
                break
            }
        }
        return t
    }
}
