package net.palaya.chessanalyzer.core.narration

import net.palaya.chessanalyzer.core.analysis.MoveClassification
import net.palaya.chessanalyzer.core.analysis.TacticType
import net.palaya.chessanalyzer.core.chess.Color
import net.palaya.chessanalyzer.core.chess.PieceType
import net.palaya.chessanalyzer.core.chess.Square

/**
 * THE NARRATION STRING CONTRACT — every word the narrated review speaks or burns into a frame is
 * one of the [Sentence]s below, rendered by a [NarrationStrings] implementation for one language.
 *
 * `:core` is Android-free, so `R.string` is not available here; this file is what stands in for
 * it, and it is deliberately *not* a string table. The rule that shaped it:
 *
 * **A locale owns whole sentences, never fragments.** Hebrew inflects verbs and adjectives for
 * gender, pluralises differently and orders words differently, so `"White " + "played " + move`
 * cannot be translated piecewise no matter how good each piece is. Every [Sentence] therefore
 * carries *typed facts* (a [Subject] with person and gender, a [SpokenMove] with the piece, the
 * squares and the victim, a [Standing] enum rather than the English words for it) and a locale
 * builds the entire sentence from those facts in whatever order its grammar wants. The generator
 * never sees the words; it only chooses which sentence to say and joins finished sentences with
 * spaces.
 *
 * The English implementation is [EnglishNarration]. A translator receives:
 *  1. this file — the ids (class names), their parameters, and the English reference in the KDoc;
 *  2. `docs/NARRATION_STRINGS.md`, generated by [NarrationCatalogue] from the English
 *     implementation, one row per sentence with a rendered example;
 * and delivers one Kotlin object implementing [NarrationStrings]. The `when` over the sealed
 * hierarchy is exhaustive, so a sentence that was never translated is a compile error, not a
 * silent English fallback in the middle of a Hebrew review.
 *
 * Only a few things are *not* sentences and are joined by the generator: the discourse lead-ins
 * ([Sentence.ALittleLater], [Sentence.JumpTo]) that precede a beat, which are sentence adverbials
 * and read correctly as a prefix in either language; and the `.`/space that separates finished
 * sentences.
 */
interface NarrationStrings {

    /** BCP-47 tag of this language, e.g. `"en"`, `"he"`. */
    val languageTag: String

    /**
     * Every acceptable rendering of [sentence] in this language for [style], in a stable order.
     * The generator rotates through them deterministically ([PhrasePicker]) so a script does not
     * open forty beats with the same words. Never empty; a single-element list is the norm. A
     * locale may return more or fewer variants than English — the rotation adapts.
     *
     * An empty string is a legal variant only for [Sentence.Filler], and means "say nothing".
     */
    fun render(sentence: Sentence, style: NarrationStyle): List<String>

    /** The sub-sentence chess vocabulary this language uses; see [SpokenVocabulary]. */
    val vocabulary: SpokenVocabulary
}

/**
 * The parts of chess speech that are needed *outside* a whole sentence: by [NotationGuard] when
 * it has to speak notation that leaked in from a PGN tag, and by tests. Everything the generator
 * itself says goes through [NarrationStrings.render] as a whole [Sentence]; a locale is free to
 * compose these however its grammar wants inside those sentences.
 */
interface SpokenVocabulary {

    /** "f3" spoken so a TTS engine cannot misread it: English says "f three". */
    fun square(square: Square): String

    /** Lowercase piece noun: "knight". */
    fun piece(type: PieceType): String

    /** "White" / "Black". */
    fun side(color: Color): String

    /** A move as a noun phrase that can follow a verb: "knight takes the bishop on f three". */
    fun movePhrase(move: SpokenMove, includeOutcome: Boolean = true): String

    /** A whole variation as one breath: "pawn takes on e five, then bishop takes on f three". */
    fun linePhrase(moves: List<SpokenMove>): String

    /** Speakable form of notation that [NotationGuard] caught in free text. */
    fun spokenNotation(notation: ParsedNotation): String
}

// ---------------------------------------------------------------------------
// Typed facts that sentences carry
// ---------------------------------------------------------------------------

/** Grammatical person of a [Subject]: "you" or "White". */
enum class Person { SECOND, THIRD }

/**
 * Grammatical gender of a [Subject]. English never reads it; Hebrew must, because "you played"
 * is a different verb form for a woman than for a man. [UNSPECIFIED] is the honest default and
 * a locale should pick its conventional neutral form for it.
 */
enum class Gender { UNSPECIFIED, MASCULINE, FEMININE }

/**
 * Who a sentence is about. [person] is [Person.SECOND] when the viewer played this side and the
 * narration addresses them directly, [Person.THIRD] when the side is named by colour. [gender]
 * comes from [NarrationOptions.viewerGender] for the viewer and is [Gender.UNSPECIFIED] for the
 * opponent.
 */
data class Subject(
    val color: Color,
    val person: Person,
    val gender: Gender = Gender.UNSPECIFIED
)

enum class CastleSide { KINGSIDE, QUEENSIDE }

enum class MoveOutcome { NONE, CHECK, CHECKMATE }

/**
 * A move as facts, so a locale can say it its own way. Built by [SpokenChess.describe].
 *
 * @param captured the victim's type when this is a capture and the board knew what stood there.
 * @param ambiguous another piece of the same type could reach [to], so the origin must be spoken
 *   (the spoken equivalent of SAN disambiguation).
 */
data class SpokenMove(
    val color: Color,
    val piece: PieceType,
    val from: Square,
    val to: Square,
    val castle: CastleSide? = null,
    val isCapture: Boolean = false,
    val captured: PieceType? = null,
    val enPassant: Boolean = false,
    val promotion: PieceType? = null,
    val ambiguous: Boolean = false,
    val outcome: MoveOutcome = MoveOutcome.NONE
)

/** The verb a [Sentence.Played] uses. Semantic choices; a locale may render several the same. */
enum class MoveVerb { PLAY, GO_FOR, ANSWER_WITH, CONTINUE_WITH, REPLY_WITH, FOLLOW_UP_WITH, FIND }

/** Where in a missed-tactic excursion a [Sentence.ExcursionMove] sits. */
enum class ExcursionStep { FIRST, NEXT, REPLY }

/** How good a position is for its owner, from win-percent. See [NarrationVocabulary.standing]. */
enum class Standing {
    COMPLETELY_WINNING, WINNING, CLEARLY_BETTER, A_LITTLE_BETTER, ABOUT_LEVEL,
    SLIGHTLY_WORSE, CLEARLY_WORSE, LOSING, COMPLETELY_LOST
}

/** How much a move gave away. See [NarrationVocabulary.lossSeverity]. */
enum class LossSeverity { THE_WHOLE_GAME, MOST_OF_THE_ADVANTAGE, A_BIG_CHUNK, REAL_GROUND, A_LITTLE }

/** Spoken size of a tactic's material payoff. See [NarrationVocabulary.materialPayoff]. */
enum class MaterialPayoff { WHOLE_QUEEN, ROOK, PIECE, SERIOUS_MATERIAL, PAWN, BETTER_POSITION }

/** Material actually netted along a line, by unit. See [NarrationVocabulary.materialGain]. */
enum class MaterialGain { QUEEN, ROOK, PIECE, PAWN }

/** What a missed line delivers when it does not simply cash material or mate. */
enum class PayoffKind {
    DRAW_BY_REPETITION, STALEMATE, DESPERADO, PASSED_PAWN, SMALL_MATERIAL,
    KING_UNDER_FIRE, MATING_NET, INVESTED_MATERIAL, DECISIVE_ADVANTAGE
}

/** The prize a puzzle prompt promises. */
enum class PuzzlePrize { FORCES_MATE, WINS_ROOK_OR_BETTER, WINS_PIECE, WINS_MATERIAL }

/**
 * Opening families the narration has a plan blurb for, matched by substring of the book name
 * (first match wins, so specific names precede general ones). See
 * [NarrationVocabulary.openingFamily].
 */
enum class OpeningFamily(vararg val keywords: String) {
    PHILIDOR("Philidor"),
    PETROV("Petrov", "Russian Game"),
    RUY_LOPEZ("Ruy Lopez", "Spanish"),
    ITALIAN("Italian", "Giuoco"),
    SCOTCH("Scotch"),
    FOUR_KNIGHTS("Four Knights"),
    VIENNA("Vienna"),
    KINGS_GAMBIT("King's Gambit"),
    SICILIAN("Sicilian"),
    FRENCH("French"),
    CARO_KANN("Caro-Kann"),
    SCANDINAVIAN("Scandinavian"),
    PIRC_MODERN("Pirc", "Modern"),
    ALEKHINE("Alekhine"),
    QUEENS_GAMBIT("Queen's Gambit"),
    SLAV("Slav"),
    NIMZO("Nimzo"),
    KINGS_INDIAN("King's Indian"),
    GRUNFELD("Grunfeld"),
    BENONI("Benoni"),
    DUTCH("Dutch"),
    LONDON("London"),
    ENGLISH("English"),
    RETI("Reti"),
    BIRD("Bird")
}

/** Notation that [NotationGuard] found in free text, parsed so a locale can speak it. */
sealed interface ParsedNotation {
    data class Castle(val side: CastleSide) : ParsedNotation

    /** Nf3, Rad1, R1xd7, Qxh5+, e8=Q as a piece move. [fromFile] is 'a'..'h', [fromRank] 1..8. */
    data class PieceMove(
        val piece: PieceType,
        val fromFile: Char?,
        val fromRank: Int?,
        val capture: Boolean,
        val to: Square,
        val promotion: PieceType?,
        val outcome: MoveOutcome
    ) : ParsedNotation

    /** dxe5, exd8=Q+. */
    data class PawnCapture(val fromFile: Char, val to: Square, val promotion: PieceType?, val outcome: MoveOutcome) : ParsedNotation

    /** e8=Q, e4+ — a pawn push that carried a promotion or a check mark. */
    data class PawnPush(val to: Square, val promotion: PieceType?, val outcome: MoveOutcome) : ParsedNotation

    /** A bare "e4" in prose. */
    data class BareSquare(val square: Square) : ParsedNotation
}

// ---------------------------------------------------------------------------
// The sentences
// ---------------------------------------------------------------------------

/**
 * Every sentence the review can say. The class name is the sentence id; the constructor
 * parameters are the facts a translation may reorder freely. The English in each KDoc is the
 * reference rendering (one variant where there are several).
 *
 * Percentages and accuracies arrive pre-formatted to one decimal ("59.9") because the digits
 * are the same in every target language; move numbers and counts arrive as integers so a locale
 * can pluralise.
 */
sealed interface Sentence {

    /** Key under which [PhrasePicker] rotates this sentence's variants. */
    val poolKey: String get() = this::class.simpleName ?: "sentence"

    // -- On-screen text produced by the generator: title, chapters, captions, cards -------

    /** "MorphyFan vs DukeAndCount" */
    data class VideoTitle(val white: String, val black: String) : Sentence

    /** "Philidor Defense (C41) · 1-0 · analysed at depth 18" */
    data class VideoSubtitle(val openingName: String?, val eco: String?, val result: String?, val depth: Int) : Sentence

    data object ChapterIntro : Sentence
    data object ChapterOpening : Sentence
    data object ChapterMiddlegame : Sentence

    /** "Move 12: Nf3" */
    data class ChapterMove(val moveNumber: Int, val san: String) : Sentence
    data object ChapterTurningPoint : Sentence
    data object ChapterDamageReport : Sentence
    data object ChapterWorkOn : Sentence

    /** "Philidor Defense (C41)" — a title-card line. */
    data class CardOpeningLine(val name: String, val eco: String?) : Sentence

    /** "1-0 · 34 plies" */
    data class CardResultLine(val result: String, val plies: Int) : Sentence

    /** "White 85.0% · Black 80.1%" */
    data class CardAccuracyLine(val whiteAccuracy: String, val blackAccuracy: String) : Sentence

    /** "Philidor Defense (C41)", or "Opening" when the book had no name. */
    data class CaptionOpening(val name: String?, val eco: String?) : Sentence

    /** "Moves 5–9" */
    data class CaptionMoves(val fromMove: Int, val toMove: Int) : Sentence

    /** "12. Nf3" for White, "12... Nf3" for Black; [glyph] appends the classification mark. */
    data class CaptionMove(val moveNumber: Int, val color: Color, val san: String, val glyph: String? = null) : Sentence

    /** "Missed: Nf3 (played e4)", or "What was missed" without a best move. */
    data class CaptionMissed(val bestSan: String?, val playedSan: String) : Sentence

    /** "Missed line — Nf3 e5 Nxe5" */
    data class CaptionMissedLine(val sans: List<String>) : Sentence

    /** "Back to the game — 12. Nf3" */
    data class CaptionBackToGame(val moveNumber: Int, val color: Color, val san: String) : Sentence

    /** "White to play — can you find it?" */
    data class CaptionPuzzle(val side: Color) : Sentence

    /** "Turning point — move 12 Nf3 (31.5% swing)" */
    data class CaptionTurningPoint(val moveNumber: Int, val san: String, val lossPercent: String) : Sentence

    /** "White 85.0% (1650) · Black 80.1% (1500)" */
    data class CaptionOutro(val whiteAccuracy: String, val whiteRating: Int, val blackAccuracy: String, val blackRating: Int) : Sentence

    /** "Takeaway 1 of 3" */
    data class CaptionTakeaway(val index: Int, val total: Int) : Sentence

    /** "Final numbers" */
    data object CardFinalNumbersHeading : Sentence

    /** "MorphyFan — 85.0%, est. 1650" */
    data class CardFinalPlayerLine(val name: String, val accuracy: String, val rating: Int) : Sentence

    /** "Blunders 1–2 · Mistakes 0–1" */
    data class CardFinalCountsLine(val whiteBlunders: Int, val blackBlunders: Int, val whiteMistakes: Int, val blackMistakes: Int) : Sentence

    /** "What to work on" */
    data object CardWorkOnHeading : Sentence

    // -- Intro ----------------------------------------------------------------------------

    /** "No names on this one, so it's White against Black." */
    data object IntroNoNames : Sentence

    /** "MorphyFan has the white pieces, rated 1650. DukeAndCount is on the other side, rated 1500." */
    data class IntroPlayers(val white: String, val whiteRating: Int?, val black: String, val blackRating: Int?) : Sentence

    /** "White won it in 17 moves." / "White finished it with mate in 17 moves." */
    data class ResultDecisive(val winner: Color, val byMate: Boolean, val fullMoves: Int) : Sentence

    /** "It ended in a draw after 40 moves." */
    data class ResultDraw(val fullMoves: Int) : Sentence

    /** "The game runs 23 moves and stops there." */
    data class ResultUnfinished(val fullMoves: Int) : Sentence

    /** "You were White here, so that's the side we're watching." — always second person. */
    data class IntroYouWere(val subject: Subject) : Sentence

    /** "And somewhere in here there's a forced mate that never got played. We'll get to it." */
    data object HookMissedMate : Sentence

    /** "But this whole game turns on one move, around move 23, and I'd bet most people walk straight past it." */
    data class HookBigTurn(val moveNumber: Int) : Sentence

    /** "It's closer than the result makes it look. One moment, around move 23, decides it." */
    data class HookClose(val moveNumber: Int) : Sentence

    /** "This one is clean from both sides, but there's still a crack in it, and we're going to find it." */
    data object HookClean : Sentence

    /** "Not a mistake in sight from either player. So let's talk about what they both got right." */
    data object HookNoMistakes : Sentence

    // -- Opening --------------------------------------------------------------------------

    /** "This is the Philidor Defense." */
    data class OpeningLead(val name: String) : Sentence

    /** "No book name for this one." */
    data object OpeningNoBookName : Sentence

    /** The family's plan blurb: "Black props the centre up with the d-pawn instead of a knight. ..." */
    data class OpeningPlan(val family: OpeningFamily) : Sentence

    /** "White opened with pawn to e four, Black answered with pawn to e five, and from there it's a fight ..." */
    data class OpeningGeneric(val whiteFirst: SpokenMove, val blackFirst: SpokenMove) : Sentence

    /** "Both sides go for the centre and the faster development." */
    data object OpeningGenericNoMoves : Sentence

    /** "Both sides just developed." — an empty game. */
    data object OpeningBothDeveloped : Sentence

    /** "Theory runs out around move 8." */
    data class TheoryRunsOut(val moveNumber: Int) : Sentence

    // -- Connectives between beats ---------------------------------------------------------

    /** "The next few moves are just development and shuffling. Nothing breaks, so let's jump to move 14." */
    data class SkipAhead(val moveNumber: Int) : Sentence

    /** Lead-in fragment before a beat in MISTAKES_ONLY: "Forward to move 14. " */
    data class JumpTo(val moveNumber: Int) : Sentence

    /** Lead-in fragment before a beat: "A couple of moves later, " */
    data object ALittleLater : Sentence

    // -- The move that was played ----------------------------------------------------------

    /**
     * "White plays knight to f three" / "you take the knight on f three with the bishop" /
     * "Black castles kingside". The one sentence every beat starts from. [recapture] swaps in
     * "takes back", which keeps an exchange from being narrated as four hanging pieces.
     */
    data class Played(val subject: Subject, val verb: MoveVerb, val move: SpokenMove, val recapture: Boolean = false) : Sentence

    /** "White plays on" — the move text was unavailable (a malformed PGN move); the beat still runs. */
    data class PlayedUnknown(val subject: Subject, val verb: MoveVerb) : Sentence

    // -- Flavour after a quiet move --------------------------------------------------------

    /** "Still theory." */
    data object StillTheory : Sentence

    /** "That was the only legal move, so there's no decision to make." */
    data object OnlyLegalMove : Sentence

    /** "King's tucked away." */
    data object KingTuckedAway : Sentence

    /** "And that is a brilliant move. It gives material away and the engine loves it anyway." */
    data object BrilliantFlavour : Sentence

    /** "That was the only move that held, and it got found." */
    data object GreatFlavour : Sentence

    /** "Top of the engine's list." */
    data object BestFlavour : Sentence

    /** "Check, so the reply is forced." */
    data object CheckForcesReply : Sentence

    /** "Sensible." — coach filler; one variant is empty, meaning say nothing. */
    data object Filler : Sentence

    // -- Mate -----------------------------------------------------------------------------

    /** "And that's the game." */
    data object MateClosing : Sentence

    /** "You finish it off." / "White wins." */
    data class MateFinish(val subject: Subject) : Sentence

    /** "And that's you on the receiving end of it." */
    data object MateOnReceivingEnd : Sentence

    // -- A tactic that was found -------------------------------------------------------------

    /** "That's just the trade going through." */
    data object JustTheTrade : Sentence

    /** "Nothing was defending it." */
    data object NothingDefendingIt : Sentence

    /** "That's a rook in the bank." */
    data class MaterialInTheBank(val payoff: MaterialPayoff) : Sentence

    /** "It doesn't win material yet, but the pressure is real." */
    data object PressureNoMaterialYet : Sentence

    /** "Good, solid stuff." */
    data object GoodSolid : Sentence

    // -- Errors -----------------------------------------------------------------------------

    /** "Oh no." / "The win was sitting right there." / "Careful." by classification. */
    data class ErrorOpener(val classification: MoveClassification) : Sentence {
        override val poolKey: String get() = "ErrorOpener.$classification"
    }

    /** "White is still winning, but that gave away real ground." */
    data class ConsequenceUnchanged(val subject: Subject, val standing: Standing, val severity: LossSeverity) : Sentence

    /** "White was winning before that. Now White is about level." */
    data class ConsequenceChanged(val subject: Subject, val before: Standing, val after: Standing) : Sentence

    /** "Knight to f three was the move." */
    data class BetterWas(val move: SpokenMove) : Sentence

    /** "There was mate in three on the board, starting with queen to h five." */
    data class MateWasAvailable(val mateIn: Int, val move: SpokenMove) : Sentence

    /** ", and that's the move that lets it in." — follows a [Played] clause after a comma. */
    data object ThreatLetIn : Sentence

    /** "It's not losing, it's just loose." */
    data object InaccuracyNote : Sentence

    // -- The missed-tactic excursion ----------------------------------------------------------

    /** "Now hold on. Let's rewind, because there was something much better here." */
    data object PivotIn : Sentence

    /** "The move is knight to f three." */
    data class PivotReveal(val move: SpokenMove) : Sentence

    /** "Let's play it out." */
    data object PivotWalk : Sentence

    /**
     * One ply of the line. FIRST: "So: you play knight to f three." NEXT: "Then you play rook to
     * b one." REPLY: "Black answers with the king taking on d one."
     */
    data class ExcursionMove(val subject: Subject, val verb: MoveVerb, val move: SpokenMove, val step: ExcursionStep, val recapture: Boolean = false) : Sentence {
        override val poolKey: String get() = "ExcursionMove.$step"
    }

    /** "The king has nowhere left to go, and the line stops there." */
    data object LineEndsInMate : Sentence

    /** "That is a rook off the board." — null gain reads "material". */
    data class MaterialTaken(val gain: MaterialGain?) : Sentence

    /** "The king has to answer that first, which is the whole point of the move order." */
    data object CheckMustBeAnswered : Sentence

    /** "White is already a piece up here, and the pressure is not going away." */
    data class AlreadyUp(val subject: Subject, val gain: MaterialGain?) : Sentence

    /** "No fireworks. It just keeps everything pointed at the same weakness." */
    data object QuietMove : Sentence

    /** "There is nothing else legal." */
    data object OnlyLegalReply : Sentence

    /** "Forced — the king was in check, so nothing else was even legal." */
    data object ForcedByCheck : Sentence

    /** "Taking back is the natural answer, and it changes nothing." */
    data object RecaptureNatural : Sentence

    /** "That is the best defence on offer." */
    data object BestDefence : Sentence

    /** Lead-in fragment to the payoff: "And there it is. " */
    data object PayoffLead : Sentence

    /** "That is checkmate in two." */
    data class PayoffMate(val mateIn: Int) : Sentence

    /** "You come out of it a rook up, for nothing." */
    data class PayoffMaterial(val subject: Subject, val gain: MaterialGain?) : Sentence

    /** "White forces a draw by repetition." / "You end up completely on top." by [kind]. */
    data class PayoffOutcome(val subject: Subject, val kind: PayoffKind) : Sentence

    /** "And there was mate in four behind it." */
    data class MateBehindIt(val mateIn: Int) : Sentence

    /** "Back in the real game, though, that got played instead —" */
    data object PivotOut : Sentence

    /** "And the chance is gone. It does not come back." */
    data object ChanceGone : Sentence

    /** "Instead, White plays knight to c three, and it's gone." — the no-line fallback. */
    data class InsteadPlayed(val subject: Subject, val move: SpokenMove, val recapture: Boolean = false) : Sentence

    /**
     * One spoken sentence about a motif: "The knight on f three has nothing defending it."
     * [target] is the motif's first target square, [victim] what stood on it, [second] the second
     * target of a fork.
     */
    data class TacticPoint(val type: TacticType, val target: Square?, val victim: PieceType?, val second: Square?) : Sentence {
        override val poolKey: String get() = "TacticPoint.$type"
    }

    /** The concrete takeaway for a motif: "Any time two of your opponent's big pieces sit a knight's jump apart ..." */
    data class TacticLesson(val type: TacticType) : Sentence

    /** "There's a clean textbook fork waiting in the game report if you want to see the pattern on its own." */
    data class TextbookOffer(val type: TacticType) : Sentence

    // -- Puzzle prompt ---------------------------------------------------------------------

    /** "White to play. There is a move here that wins a whole piece. Pause the video. Can you find it?" */
    data class PuzzlePrompt(val side: Color, val prize: PuzzlePrize) : Sentence

    // -- Turning point -----------------------------------------------------------------------

    /** "And that is the turning point of the whole game. " */
    data object TurningPointLead : Sentence

    /** "Nothing else in this game swings the evaluation like move 23." */
    data class TurningPointSwing(val moveNumber: Int) : Sentence

    /** "White went from winning to about level on one move." */
    data class TurningPointFromTo(val subject: Subject, val before: Standing, val after: Standing) : Sentence

    // -- Outro ------------------------------------------------------------------------------

    /** "Right, numbers. " */
    data object OutroLead : Sentence

    /** "MorphyFan finished on 85.0 percent accuracy, DukeAndCount on 80.1 percent." */
    data class OutroAccuracy(val white: String, val whiteAccuracy: String, val black: String, val blackAccuracy: String) : Sentence

    /** "That's play at roughly 1650 and 1500." */
    data class OutroRatings(val whiteRating: Int, val blackRating: Int) : Sentence

    /** "MorphyFan did not make a single mistake the engine cares about." */
    data class NoMistakes(val name: String) : Sentence

    /** "MorphyFan had one blunder, two mistakes and one missed win." — zero counts are omitted. */
    data class ErrorCounts(val name: String, val blunders: Int, val mistakes: Int, val misses: Int, val inaccuracies: Int) : Sentence

    /** "It's a short game, so treat those rating estimates as a rough guide rather than gospel." */
    data object ShortGameCaveat : Sentence

    // -- Lessons ------------------------------------------------------------------------------

    /** Lead-in fragment before the first lesson: "So what do you take away from this? " */
    data object LessonLead : Sentence

    /** "You walked past three forks in this game. They were on e five, c seven and f three." */
    data class LessonRepeatedMiss(val subject: Subject, val type: TacticType, val count: Int, val squares: List<Square>) : Sentence

    /** "The one thing you left on the board was a fork at move 12. The one that hurt was on e five." */
    data class LessonSingleMiss(val subject: Subject, val type: TacticType, val moveNumber: Int?, val square: Square?) : Sentence

    /** "Every one of your three errors came after move 10, once the pieces were out ..." */
    data class LessonLateErrors(val subject: Subject, val count: Int, val afterMove: Int) : Sentence

    /** "Your mistakes ran from move 4 to move 30, so they're spread right across the game ..." */
    data class LessonSpreadErrors(val subject: Subject, val firstMove: Int, val lastMove: Int) : Sentence

    /** "One mistake. Move 23 cost 31.5 percent of the position on its own, and everything else you played was fine. ..." */
    data class LessonOneMistake(val subject: Subject, val moveNumber: Int, val lossPercent: String) : Sentence

    /** "You handed over a tactic three times in this game — moves that were fine in themselves but let something in. ..." */
    data class LessonGifts(val subject: Subject, val count: Int) : Sentence

    /** "You got mated at the end, but the mate wasn't the mistake — move 23 was. ..." */
    data class LessonMatedButNotTheMistake(val subject: Subject, val turningMove: Int) : Sentence

    /** "Worth knowing: the other side left two forks on the board too, and you converted one chance of your own. ..." */
    data class LessonOpponentMissedToo(val subject: Subject, val type: TacticType, val count: Int, val converted: Int) : Sentence

    /** "You found the engine's top move five times out of 17, for 85.0 percent. ..." */
    data class LessonPositive(val subject: Subject, val bestMoves: Int, val totalMoves: Int, val accuracy: String) : Sentence

    /** "You came out of this at 85.0 percent, which the model reads as about 1650. ..." */
    data class LessonRatingAnchor(val subject: Subject, val accuracy: String, val rating: Int) : Sentence
}

/**
 * The languages the narration can be generated in. Adding one is: implement [NarrationStrings],
 * add it to [all]. The app resolves its language setting through [forTag].
 */
object NarrationLocales {

    val all: List<NarrationStrings> = listOf(EnglishNarration)

    val default: NarrationStrings = EnglishNarration

    /**
     * The narration for a BCP-47 tag, matching on the language subtag only (`"en-GB"` → English).
     * Hebrew arrives from Android as either `"he"` or the legacy `"iw"`; both resolve alike once
     * a Hebrew implementation exists. Unknown or null tags fall back to [default].
     */
    fun forTag(tag: String?): NarrationStrings {
        val language = tag?.substringBefore('-')?.substringBefore('_')?.lowercase()?.let(::canonicalLanguage)
            ?: return default
        return all.firstOrNull { canonicalLanguage(it.languageTag.substringBefore('-').lowercase()) == language } ?: default
    }

    /** Android's legacy codes to their ISO 639-1 successors. */
    private fun canonicalLanguage(code: String): String = when (code) {
        "iw" -> "he"
        "in" -> "id"
        "ji" -> "yi"
        else -> code
    }
}
